### PR TITLE
feat: Chainflip integration

### PR DESCRIPTION
**Pull request by tien**

### CODE REVIEW

**Comment by prury** [comment]
Select destination field doesn't let you choose existent ethereum accounts nor it lets you type an ethereum address: 
same if i invert the account/destination field

image

**Comment by tien** [comment]
> Select destination field doesn't let you choose existent ethereum accounts nor it lets you type an ethereum address: same if i invert the account/destination field

You need to connect the account via the EVM connector, not substrate. But destination account can come from anywhere, so I've made a change for that.

**Comment by prury** [comment]
@tien  please provide new deployment link, it seems that it was not automatically generated

**Comment by prury** [comment]
first try went ok i guess: 

image

https://scan.perseverance.chainflip.io/channels/778405-Ethereum-17

**Review by jonathanpdunne — APPROVED** [review]

**Pull request merged**
