### PR TITLE
Use talisman extension preferentially

### PR DESCRIPTION
**Pull request by chidg**
Updated `src/libs/talisman/extension.tsx` to use [Talisman Connect]("https://github.com/TalismanSociety/connect") and preferentially call the Talisman extension only. Will revert back to default behaviour of using Polkadot.js and/or other extensions if Talisman not found.

### CODE REVIEW

**Comment by chidg** [comment]
> ❌ Deploy Preview for _talisman-web_ failed.
Looks like `yarn install` in Netlify is not able to pull a dependency from Github.

Are we able to publish @talismn/connect to NPM?  @alecdwm @daniel-flex

**Review by alecdwm — APPROVED** [review]
Looks great to me!

We'll need to update [this import](https://github.com/TalismanSociety/talisman-web/blob/22622dbfdb681d68a2012864640872ac96b4266a/src/libs/moonbeam-contributors/index.tsx#L9) to `@talismn/dapp-connect` before merging to latest prod

**Comment by alecdwm** [comment]
Ah, also need to update the imports [here](https://github.com/TalismanSociety/talisman-web/blob/22622dbfdb681d68a2012864640872ac96b4266a/src/routes/SpiritKeysPage.tsx#L8) and [here](https://github.com/TalismanSociety/talisman-web/blob/22622dbfdb681d68a2012864640872ac96b4266a/src/libs/crowdloans/moonbeam/remarkFlow.ts#L5)

**Comment by chidg** [comment]
> Ah, also need to update the imports [here](https://github.com/TalismanSociety/talisman-web/blob/22622dbfdb681d68a2012864640872ac96b4266a/src/routes/SpiritKeysPage.tsx#L8) and [here](https://github.com/TalismanSociety/talisman-web/blob/22622dbfdb681d68a2012864640872ac96b4266a/src/libs/crowdloans/moonbeam/remarkFlow.ts#L5)

Thanks, had done, just hadn't pushed 🤦

**Pull request merged**
